### ISSUE TITLE
unable to get to work

### ISSUE THREAD

**Issue by trustdan** [anvlkv/polymathic#22]
I've followed the instructions, run NPM install and the rest of it, tried submodule add, copying the directory over to the themes directory, and a few other things.  Can't get it to look different from the normal blank zola to save my life.

**Comment by anvlkv** [comment]
Hi, the simplest you could do is fork the demo repo and replace the content. You may need to drop some of the templates overrides.

Alternatively you can share a link to your usecase. I'd be happy to take a look.

**Comment by anvlkv** [comment]
Once you've forked the demo you would still need to run npm install as described here https://polymathic-demo.netlify.app/docs/install/
